export const FACE_DETECTION_INTERVAL_MS = 250;
export const FACE_DETECTION_MIN_CONFIDENCE = 0.6;
export const FACE_MIN_WIDTH_RATIO = 0.2;
export const FACE_MIN_INSIDE_RATIO = 0.7;

export const FACE_MATCH_THRESHOLD = 0.62;
export const FACE_MATCH_MARGIN = 0.08;
export const PREDICTION_WINDOW_SIZE = 5;
export const PREDICTION_REQUIRED_MATCHES = 4;
export const IDENTITY_CLEAR_MS = 1_000;
